// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2qO2lX5j6PZ-BOOD91GdZgSVEegJQgsE',
    appId: '1:173890793231:web:9e417b6a68c7541b59587a',
    messagingSenderId: '173890793231',
    projectId: 'flutter-pro-firebase-aefab',
    authDomain: 'flutter-pro-firebase-aefab.firebaseapp.com',
    databaseURL: 'https://flutter-pro-firebase-aefab-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-pro-firebase-aefab.firebasestorage.app',
    measurementId: 'G-SFYP361GN9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC17UWq-wRPy04N1qsmlfFCfpIxD3dxGVI',
    appId: '1:173890793231:android:834b8a5e4fdeaa2959587a',
    messagingSenderId: '173890793231',
    projectId: 'flutter-pro-firebase-aefab',
    databaseURL: 'https://flutter-pro-firebase-aefab-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-pro-firebase-aefab.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6l_kWXwTEXZDS5Kzzje_I7D6R0CaCC-4',
    appId: '1:173890793231:ios:c5e73130bb8eeb5959587a',
    messagingSenderId: '173890793231',
    projectId: 'flutter-pro-firebase-aefab',
    databaseURL: 'https://flutter-pro-firebase-aefab-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-pro-firebase-aefab.firebasestorage.app',
    androidClientId: '173890793231-gdt1vnolo5r7fosgrsv2lq4r2dc5lmk1.apps.googleusercontent.com',
    iosClientId: '173890793231-cev9jb42t5mtivenfkpihfrm6655bjcv.apps.googleusercontent.com',
    iosBundleId: 'com.example.testapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6l_kWXwTEXZDS5Kzzje_I7D6R0CaCC-4',
    appId: '1:173890793231:ios:c5e73130bb8eeb5959587a',
    messagingSenderId: '173890793231',
    projectId: 'flutter-pro-firebase-aefab',
    databaseURL: 'https://flutter-pro-firebase-aefab-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-pro-firebase-aefab.firebasestorage.app',
    androidClientId: '173890793231-gdt1vnolo5r7fosgrsv2lq4r2dc5lmk1.apps.googleusercontent.com',
    iosClientId: '173890793231-cev9jb42t5mtivenfkpihfrm6655bjcv.apps.googleusercontent.com',
    iosBundleId: 'com.example.testapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA2qO2lX5j6PZ-BOOD91GdZgSVEegJQgsE',
    appId: '1:173890793231:web:bbb49388906b0ad159587a',
    messagingSenderId: '173890793231',
    projectId: 'flutter-pro-firebase-aefab',
    authDomain: 'flutter-pro-firebase-aefab.firebaseapp.com',
    databaseURL: 'https://flutter-pro-firebase-aefab-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-pro-firebase-aefab.firebasestorage.app',
    measurementId: 'G-L230JLNKM4',
  );
}
