import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';

class AppLocalization {
  static const String _languageKey = 'selected_language';
  static const String _supportedLanguages = 'en,fil';
  
  static const Map<String, String> _englishStrings = {
    'appTitle': 'KwentoPinoy',
    'welcomeBack': 'Welcome Back!',
    'weMissedYou': 'We Missed You! 😊',
    'email': 'Email',
    'password': 'Password',
    'confirmPassword': 'Confirm Password',
    'login': 'Log In',
    'signup': 'Sign Up',
    'signupButton': 'Create Account',
    'continueWithGoogle': 'Continue with Google',
    'dontHaveAccount': "Don't have an account?",
    'haveAccount': 'Already have an account?',
    'forgotPassword': 'Forgot Password?',
    'resetPassword': 'Reset Password',
    'sendResetLink': 'Send Reset Link',
    'checkEmail': 'Check your email for password reset instructions',
    'dictionary': 'Dictionary',
    'home': 'Home',
    'favorites': 'Favorite Stories',
    'profile': 'My Profile',
    'search': 'Search',
    'searchStories': 'Search stories...',
    'categories': 'Categories',
    'stories': 'Stories',
    'allStories': 'All Stories',
    'seeAll': 'See All',
    'recentSearches': 'Recent Searches',
    'clearAll': 'Clear All',
    'noResults': 'No results found',
    'loading': 'Loading...',
    'error': 'Error',
    'tryAgain': 'Try Again',
    'logout': 'Log Out',
    'editProfile': 'Edit Profile',
    'changePassword': 'Change Password',
    'currentPassword': 'Current Password',
    'newPassword': 'New Password',
    'save': 'Save',
    'cancel': 'Cancel',
    'delete': 'Delete',
    'add': 'Add',
    'edit': 'Edit',
    'close': 'Close',
    'back': 'Back',
    'next': 'Next',
    'previous': 'Previous',
    'done': 'Done',
    'ok': 'OK',
    'yes': 'Yes',
    'no': 'No',
    'username': 'Username',
    'displayName': 'Display Name',
    'uploadPhoto': 'Upload Photo',
    'selectPhoto': 'Select Photo',
    'language': 'Language',
    'english': 'English',
    'tagalog': 'Tagalog',
    'settings': 'Settings',
    'about': 'About',
    'privacyPolicy': 'Privacy Policy',
    'termsOfService': 'Terms of Service',
    'contactUs': 'Contact Us',
    'version': 'Version',
    'oopsError': 'Oops! An Error Occurred',
    'accountDeleted': 'Account successfully deleted',
    'passwordChanged': 'Password successfully changed',
    'profileUpdated': 'Profile successfully updated',
    'noFavorites': 'No favorite stories yet',
    'addToFavorites': 'Add to Favorites',
    'removeFromFavorites': 'Remove from Favorites',
    'shareStory': 'Share Story',
    'readMore': 'Read More',
    'lesson': 'Lesson',
    'vocabulary': 'Vocabulary',
    'quiz': 'Quiz',
    'narration': 'Narration',
    'startQuiz': 'Start Quiz',
    'yourScore': 'Your Score',
    'correct': 'Correct',
    'incorrect': 'Incorrect',
    'totalQuestions': 'Total Questions',
    'backToLogin': 'Back to Login',
    'resetLinkSent': 'Reset Link Sent',
    'passwordResetInstructions': 'A password reset link has been sent to your email address. Please check your inbox.',
    'enterEmailReset': 'Enter your email to receive a password reset link.',
    'invalidEmailFormat': 'Invalid email format',
    'pleaseEnterEmail': 'Please enter your email',
    'loginError': 'Login Error',
    'signupError': 'Signup Error',
    'createAccount': 'Create Account',
    'letsGetStarted': "Let's Get Started!",
    'yourAwesomeName': 'Your awesome name',
    'pleaseEnterUsername': 'Please enter your username',
    'pleaseEnterValidEmail': 'Please enter your email',
    'pleaseEnterPassword': 'Please enter your password',
    'passwordsDontMatch': "Passwords don't match",
    'confirmPasswordPlease': 'Please confirm your password',
    'enterCurrentPassword': 'Enter current password',
    'enterNewPassword': 'Enter new password',
    'passwordMinChars': 'Must be at least 6 characters',
    'logoutError': 'Logout Error',
    'failedToLogout': 'Failed to logout',
    'deleteAccount': 'Delete Account',
    'deleteAccountConfirm': 'Are you sure you want to delete your account? This action cannot be undone.',
    'myDictionary': 'My Dictionary',
    'storyQuizzes': 'Story Quizzes',
    'noQuizFound': 'No Quiz Found',
    'loadingQuiz': 'Loading Quiz...',
    'noQuizDataAvailable': 'No quiz data available for this story.',
    'quizComplete': 'Quiz Complete!',
    'noStoriesMatching': 'No stories match your filters',
    'noStoriesFound': 'No stories found',
    'filterByCategory': 'Filter by Category:',
    'filterByReadStatus': 'Filter by Read Status:',
    'status': 'Status:',
    'continueReading': 'Continue Reading',
    'score': 'Score:',
    'question': 'Question',
    'of': 'of',
    'fable': 'Fable',
    'folktale': 'Folktale',
    'legend': 'Legend',
    'myProfile': 'My Profile',
    'unread': 'Unread',
    'read': 'Read',
    'uncategorized': 'Uncategorized',
    'noFavoritesFound': 'No favorite stories found',
    'finish': 'Finish',
    'noStoriesFoundMatching': 'No stories found matching',
    'comingSoon': 'Coming Soon!',
    'quizComingSoon': 'Quiz feature is coming soon for this story! Stay tuned.',
    'loadingStory': 'Loading story...',
    'favorited': 'Favorited',
    'favorite': 'Favorite',
    'storyComplete': 'Hooray! You finished the story',
    'noStoryContentAvailable': 'No story content available',
    'swipeToTurnPage': 'Swipe to turn page',
    'imageNotFound': 'Image not found',
    'history': 'History',
    'exploreCategories': 'Explore Categories',
    'newStories': 'New Stories',
    'recentlyViewed': 'Recently Viewed',
    'recommendedForYou': 'Recommended For You',
    'completedStories': 'Completed Stories',
    'errorOccurred': 'Error Occurred',
    'failedToLoadContent': 'Failed to load content',
    'loadingStories': 'Loading stories...',
    'noStoriesInCategory': 'No stories found in this category',
    'unableToLoadStories': 'Unable to load stories. Please check your connection and try again.',
    'dailyChallenge': 'Daily Challenge',
    'challengeComplete': 'Challenge Complete',
    'storiesReadToday': 'Stories Read Today',
    'typeEnglishWord': 'Type the English word',
    'typeTagalogWord': 'Type the Tagalog word',
    'tapToSeeMeaning': 'Tap to see meaning',
    'clearRecentSearches': 'Clear Recent Searches',
    'searchForDefinition': 'Search for definition...',
    'tryExample': 'Try Example',
    'englishDictionary': 'English Dictionary',
    'tagalogDictionary': 'Tagalog Dictionary',
    'reAuthenticate': 'Re-authenticate',
    'confirmDeleteAccount': 'Confirm Delete Account',
    'errorDeletingAccount': 'Error deleting account',
    'failedDeleteAccount': 'Failed to delete account',
    'resetLinkSentMsg': 'A password reset link has been sent to your email',
    'joinTheFun': 'Join the fun!',
    'createAwesomeAccount': 'Create your awesome account',
    'uploadProfilePicture': 'Upload Profile Picture',
    'noTitle': 'No Title',
    'percentageCompleted': '% Completed',
    'greatJob': 'Great job! You read a story today',
    'readStoriesToday': 'Read 1 story',
    'to': 'to',
    'completeChallenge': 'complete today\'s challenge',
    'currentEmail': 'Current Email',
    'newEmail': 'New Email',
    'enterNewEmail': 'Enter new email',
    'confirmNewPassword': 'Confirm New Password',
    'pleaseConfirmPassword': 'Please confirm your password',
    'passwordsDoNotMatch': 'Passwords do not match',
    'newPasswordMustBeDifferent': 'New password must be different from current password',
    'changeEmail': 'Change Email',
    'tapToClose': 'Tap to close',
    'updateYourEmail': 'Update your email address',
    'keepAccountSecure': 'Keep your account secure',
    'enterPasswordToConfirmDeletion': 'Enter your password to confirm account deletion.',
    'passwordLabel': 'Password',
    'failedToDeleteAccount': 'Failed to delete account. Error: ',
    'gallery': 'Gallery',
    'camera': 'Camera',
    'profilePictureUpdated': 'Profile picture updated! 📸',
    'errorUploadingPicture': 'Error uploading picture',
    'uploadTimedOut': 'Upload timed out - check your internet connection',
    'permissionDenied': 'Permission denied - check storage permissions',
    'passwordUpdated': 'Password updated! 🔐',
    'usernameUpdated': 'Username updated! 🎉',
    'verificationEmailSent': 'Verification email sent to ',
    'pleaseVerifyToComplete': 'Please verify to complete the change.',
    'errorChangingEmail': 'Error changing email',
    'incorrectPassword': 'Incorrect password',
    'emailAlreadyInUse': 'Email already in use',
    'currentEmailNotFound': 'Current email not found',
    'emailMustBeDifferent': 'Email must be different',
    'cancelButton': 'Cancel',
    'confirmButton': 'Confirm',
    'enterPasswordToVerify': 'Enter your password to verify',
    'updateEmailAddress': 'Update email address',
  };

  static const Map<String, String> _filipinoStrings = {
    'appTitle': 'KwentoPinoy',
    'welcomeBack': 'Maligayang pagbabalik!',
    'weMissedYou': 'Na-miss ka namin! 😊',
    'email': 'Email',
    'password': 'Password',
    'confirmPassword': 'Kumpirmahin ang Password',
    'login': 'Mag-Login',
    'signup': 'Mag-Sign Up',
    'signupButton': 'Lumikha ng Account',
    'continueWithGoogle': 'Magpatuloy sa Google',
    'dontHaveAccount': 'Wala pang account?',
    'haveAccount': 'Mayroon na akong account',
    'forgotPassword': 'Nakalimutan ang Password?',
    'resetPassword': 'I-reset ang Password',
    'sendResetLink': 'Magpadala ng Reset Link',
    'checkEmail': 'Tingnan ang iyong email para sa mga tagubilin sa pag-reset ng password',
    'dictionary': 'Diksyunaryo',
    'home': 'Tahanan',
    'favorites': 'Mga Paboritong Kuwento',
    'profile': 'Aking Profile',
    'search': 'Maghanap',
    'searchStories': 'Maghanap ng mga kuwento...',
    'categories': 'Mga Kategorya',
    'stories': 'Mga Kuwento',
    'allStories': 'Lahat ng Kuwento',
    'seeAll': 'Tingnan Lahat',
    'recentSearches': 'Mga Kamakailang Paghahanap',
    'clearAll': 'Burahin Lahat',
    'noResults': 'Walang resulta na natagpuan',
    'loading': 'Naglo-load...',
    'error': 'Error',
    'tryAgain': 'Subukan Ulit',
    'logout': 'Mag-logout',
    'editProfile': 'I-edit ang Profile',
    'changePassword': 'Baguhin ang Password',
    'currentPassword': 'Kasalukuyang Password',
    'newPassword': 'Bagong Password',
    'save': 'I-save',
    'cancel': 'Kanselahin',
    'delete': 'Tanggalin ang account',
    'add': 'Magdagdag',
    'edit': 'I-edit',
    'close': 'Sarado',
    'back': 'Bumalik',
    'next': 'Susunod',
    'previous': 'Nakaraang',
    'done': 'Tapos na',
    'ok': 'OK',
    'yes': 'Oo',
    'no': 'Hindi',
    'username': 'Username',
    'displayName': 'Pangalan na Ipapakita',
    'uploadPhoto': 'I-upload ang Larawan',
    'selectPhoto': 'Piliin ang Larawan',
    'language': 'Wika',
    'english': 'Ingles',
    'tagalog': 'Tagalog',
    'settings': 'Mga Setting',
    'about': 'Tungkol',
    'privacyPolicy': 'Patakaran sa Privacy',
    'termsOfService': 'Mga Tuntunin ng Serbisyo',
    'contactUs': 'Makipag-ugnayan sa Amin',
    'version': 'Bersyon',
    'oopsError': 'Oops! May Error',
    'accountDeleted': 'Account ay matagumpay na naalis',
    'currentEmail': 'Kasalukuyang Email',
    'newEmail': 'Bagong Email',
    'enterNewEmail': 'Magpasok ng bagong email',
    'confirmNewPassword': 'Kumpirmahin ang Bagong Password',
    'pleaseConfirmPassword': 'Mangyaring kumpirmahin ang iyong password',
    'passwordsDoNotMatch': 'Ang mga password ay hindi tumutugma',
    'newPasswordMustBeDifferent': 'Ang bagong password ay dapat na iba sa kasalukuyang password',
    'changeEmail': 'Baguhin ang Email',
    'tapToClose': 'I-tap upang isara',
    'updateYourEmail': 'I-update ang iyong email address',
    'keepAccountSecure': 'Panatilihing secure ang iyong account',
    'reAuthenticate': 'Muling i-authenticate',
    'enterPasswordToConfirmDeletion': 'Magpasok ng iyong password upang kumpirmahin ang pagtanggal ng account.',
    'passwordLabel': 'Password',
    'errorDeletingAccount': 'Error sa Pagtanggal ng Account',
    'failedToDeleteAccount': 'Nabigo sa pagtanggal ng account. Error: ',
    'gallery': 'Gallery',
    'camera': 'Camera',
    'profilePictureUpdated': 'Profile picture ay na-update na! 📸',
    'errorUploadingPicture': 'Error sa pag-upload ng larawan',
    'uploadTimedOut': 'Nag-timeout ang pag-upload - suriin ang iyong koneksyon',
    'permissionDenied': 'Ang pahintulot ay hindi ibinigay - suriin ang mga pahintulot sa storage',
    'passwordUpdated': 'Password ay na-update na! 🔐',
    'usernameUpdated': 'Username ay na-update na! 🎉',
    'verificationEmailSent': 'Ang verification email ay ipinadala sa ',
    'pleaseVerifyToComplete': 'Mangyaring i-verify upang makumpleto ang pagbabago.',
    'errorChangingEmail': 'Error sa pagbabago ng email',
    'incorrectPassword': 'Maling password',
    'emailAlreadyInUse': 'Email ay ginagamit na',
    'invalidEmailFormat': 'Invalid na format ng email',
    'currentEmailNotFound': 'Ang kasalukuyang email ay hindi nahanap',
    'emailMustBeDifferent': 'Ang email ay dapat na iba',
    'passwordChanged': 'Password ay matagumpay na binago',
    'profileUpdated': 'Profile ay matagumpay na na-update',
    'noFavorites': 'Wala pang paboritong kwento',
    'addToFavorites': 'Idagdag sa Mga Paborito',
    'removeFromFavorites': 'Alisin mula sa Mga Paborito',
    'shareStory': 'Ibahagi ang Kuwento',
    'readMore': 'Basahin pa',
    'lesson': 'Leksyon',
    'vocabulary': 'Bokabularyo',
    'quiz': 'Quiz',
    'narration': 'Pagkukuwento',
    'startQuiz': 'Simulan ang Quiz',
    'yourScore': 'Ang Iyong Puntos',
    'correct': 'Tama',
    'incorrect': 'Mali',
    'totalQuestions': 'Kabuuang Mga Tanong',
    'backToLogin': 'Bumalik sa Login',
    'resetLinkSent': 'Reset Link na Ipinadala',
    'passwordResetInstructions': 'Ang isang password reset link ay ipinadala sa iyong email address. Mangyaring tingnan ang iyong inbox.',
    'enterEmailReset': 'Ilagay ang iyong email upang makatanggap ng password reset link.',
    'pleaseEnterEmail': 'Mangyaring ilagay ang iyong email',
    'loginError': 'Login Error',
    'signupError': 'Signup Error',
    'createAccount': 'Lumikha ng Account',
    'letsGetStarted': 'Magsimula na tayo!',
    'yourAwesomeName': 'Ang iyong kahanga-hangang pangalan',
    'pleaseEnterUsername': 'Mangyaring ilagay ang iyong username',
    'pleaseEnterValidEmail': 'Mangyaring ilagay ang iyong email',
    'pleaseEnterPassword': 'Mangyaring ilagay ang iyong password',
    'passwordsDontMatch': 'Ang mga password ay hindi tumutugma',
    'confirmPasswordPlease': 'Mangyaring kumpirmahin ang iyong password',
    'enterCurrentPassword': 'Ilagay ang kasalukuyang password',
    'enterNewPassword': 'Ilagay ang bagong password',
    'passwordMinChars': 'Dapat ay hindi bababa sa 6 na character',
    'logoutError': 'Logout Error',
    'failedToLogout': 'Nabigo ang pag-logout',
    'deleteAccount': 'Tanggalin ang Account',
    'deleteAccountConfirm': 'Sigurado ka ba na gusto mong tanggalin ang iyong account? Ang aksyong ito ay hindi maaaring bawiin.',
    'myDictionary': 'Aking Diksyunaryo',
    'storyQuizzes': 'Mga Quiz sa Kuwento',
    'noQuizFound': 'Walang Quiz na Nahanap',
    'loadingQuiz': 'Naglo-load ng Quiz...',
    'noQuizDataAvailable': 'Walang data ng quiz na available para sa kuwentong ito.',
    'quizComplete': 'Quiz Tapos na!',
    'noStoriesMatching': 'Walang kuwento na tumutugma sa iyong mga filter',
    'noStoriesFound': 'Walang kuwento na nahanap',
    'filterByCategory': 'I-filter ayon sa Kategorya:',
    'filterByReadStatus': 'I-filter ayon sa Basahin ang Status:',
    'status': 'Status:',
    'continueReading': 'Magpatuloy sa Pagbabasa',
    'score': 'Puntos:',
    'question': 'Tanong',
    'of': 'ng',
    'fable': 'Pabula',
    'folktale': 'Kuwentong-Bayan',
    'legend': 'Alamat',
    'myProfile': 'Aking Profile',
    'unread': 'Hindi pa Nabasa',
    'read': 'Nabasa na',
    'uncategorized': 'Walang Kategorya',
    'noFavoritesFound': 'Walang nahanap na mga paboritong kuwento',
    'finish': 'Tapusin',
    'noStoriesFoundMatching': 'Walang kuwento na nahanap na tumutugma',
    'comingSoon': 'Darating na!',
    'quizComingSoon': 'Darating na ang quiz para sa kuwentong ito! Abangan.',
    'loadingStory': 'Naglo-load ng kuwento...',
    'favorited': 'Naka-paborito',
    'favorite': 'Paborito',
    'storyComplete': 'Yehey! Natapos mo ang kuwento',
    'noStoryContentAvailable': 'Walang nilalaman ng kuwento',
    'swipeToTurnPage': 'I-swipe para lumiko ang pahina',
    'imageNotFound': 'Hindi natagpuan ang larawan',
    'history': 'Kasaysayan',
    'exploreCategories': 'Tuklasin ang mga Kategorya',
    'newStories': 'Mga Bagong Kuwento',
    'recentlyViewed': 'Kamakailang Tiningnan',
    'recommendedForYou': 'Inirekomenda Para sa Iyo',
    'completedStories': 'Nakumpletong mga Kuwento',
    'errorOccurred': 'Nagkaroon ng Error',
    'failedToLoadContent': 'Nabigong i-load ang nilalaman',
    'loadingStories': 'Naglo-load ng mga kuwento...',
    'noStoriesInCategory': 'Walang kuwento na nahanap sa kategoryang ito',
    'unableToLoadStories': 'Hindi makakuha ng mga kuwento. Pakisuri ang iyong koneksyon at subukan muli.',
    'dailyChallenge': 'Pang-araw-araw na Hamon',
    'challengeComplete': 'Kumpleto ang Hamon',
    'storiesReadToday': 'Kuwentong Basahin Ngayong Araw',
    'typeEnglishWord': 'I-type ang salitang Ingles',
    'typeTagalogWord': 'I-type ang salitang Tagalog',
    'tapToSeeMeaning': 'Tapakin upang makita ang kahulugan',
    'clearRecentSearches': 'Burahin ang Mga Kamakailang Paghahanap',
    'searchForDefinition': 'Maghanap ng kahulugan...',
    'tryExample': 'Subukan ang Halimbawa',
    'englishDictionary': 'Diksyunaryo sa Ingles',
    'tagalogDictionary': 'Diksyunaryo sa Tagalog',
    'confirmDeleteAccount': 'Kumpirmahin ang Pagtanggal ng Account',
    'failedDeleteAccount': 'Nabigong tanggalin ang account',
    'resetLinkSentMsg': 'Isang password reset link ay ipinadala sa iyong email',
    'joinTheFun': 'Sumali sa kasiyahan!',
    'createAwesomeAccount': 'Lumikha ng iyong kahanga-hangang account',
    'uploadProfilePicture': 'I-upload ang Profile Picture',
    'noTitle': 'Walang Pamagat',
    'percentageCompleted': '% Nakumpleto',
    'greatJob': 'Maganda! Nagbasa ka ng kuwento ngayong araw',
    'readStoriesToday': 'Basahin ang 1 kuwento',
    'to': 'sa',
    'completeChallenge': 'kumpletuhin ang hamon ng araw',
    'cancelButton': 'Kanselahin',
    'confirmButton': 'Kumpirmahin',
    'enterPasswordToVerify': 'Magpasok ng iyong password upang i-verify',
    'updateEmailAddress': 'I-update ang email address',
  };

  static Future<void> setLanguage(String languageCode) async {
    final prefs = await SharedPreferences.getInstance();
    await prefs.setString(_languageKey, languageCode);
  }

  static Future<String> getLanguage() async {
    final prefs = await SharedPreferences.getInstance();
    return prefs.getString(_languageKey) ?? 'en';
  }

  static String getString(String key, {String languageCode = 'en'}) {
    if (languageCode == 'fil') {
      return _filipinoStrings[key] ?? _englishStrings[key] ?? key;
    }
    return _englishStrings[key] ?? key;
  }

  static List<String> get supportedLanguages => _supportedLanguages.split(',');

  static String getLanguageName(String code) {
    return code == 'fil' ? 'Tagalog' : 'English';
  }

  static Locale getLocale(String languageCode) {
    return Locale(languageCode);
  }
}
